In [1]:
#Importing LIbraries
import numpy as np
import pandas as pd
import sklearn

In [2]:
df=pd.read_csv('car.data.csv',sep=",",names = ["Cost", "maintenace", "door", "person","Luggage Boot","Safety","CarClass"])
print("\nThe shape of Dataframe is: ",df.shape)
print("\nFirst Few lines are :\n",df.head())

#describing the Attribute
print("\n")
print(df.info())
print("\nThe Attributes are:\n" ,df.describe())


The shape of Dataframe is:  (1728, 7)

First Few lines are :
     Cost maintenace door person Luggage Boot Safety CarClass
0  vhigh      vhigh    2      2        small    low    unacc
1  vhigh      vhigh    2      2        small    med    unacc
2  vhigh      vhigh    2      2        small   high    unacc
3  vhigh      vhigh    2      2          med    low    unacc
4  vhigh      vhigh    2      2          med    med    unacc


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
Cost            1728 non-null object
maintenace      1728 non-null object
door            1728 non-null object
person          1728 non-null object
Luggage Boot    1728 non-null object
Safety          1728 non-null object
CarClass        1728 non-null object
dtypes: object(7)
memory usage: 94.6+ KB
None

The Attributes are:
         Cost maintenace  door person Luggage Boot Safety CarClass
count   1728       1728  1728   1728         1728   1728     1728
uniq

In [3]:
print(df.columns)

Index(['Cost', 'maintenace', 'door', 'person', 'Luggage Boot', 'Safety',
       'CarClass'],
      dtype='object')


In [4]:
#Printing the unique value
for i in df.columns:
    print(df[i].value_counts())

low      432
med      432
high     432
vhigh    432
Name: Cost, dtype: int64
low      432
med      432
high     432
vhigh    432
Name: maintenace, dtype: int64
3        432
5more    432
4        432
2        432
Name: door, dtype: int64
more    576
4       576
2       576
Name: person, dtype: int64
small    576
med      576
big      576
Name: Luggage Boot, dtype: int64
low     576
med     576
high    576
Name: Safety, dtype: int64
unacc    1210
acc       384
good       69
vgood      65
Name: CarClass, dtype: int64


In [5]:
df['CarClass'].value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: CarClass, dtype: int64

In [6]:
print("\nThe Unique value in person columns are: ",df.loc[:,'person'].unique())
print("The Unique value in door columns are: ",df.loc[:,'door'].unique())
print(df.shape[0])

#Calculation of Gini Index of target
c1=(df.loc[df['CarClass']=='unacc'].count())/df.shape[0]
c2=(df.loc[df['CarClass']=='acc'].count())/df.shape[0]
c3=(df.loc[df['CarClass']=='good'].count())/df.shape[0]
c4=(df.loc[df['CarClass']=='vgood'].count())/df.shape[0]

#GiniIndex
print("\n\n The Gini Index is ",1-(c1**2+c2**2+c4**2+c3**2))


The Unique value in person columns are:  ['2' '4' 'more']
The Unique value in door columns are:  ['2' '3' '4' '5more']
1728


 The Gini Index is  Cost            0.457284
maintenace      0.457284
door            0.457284
person          0.457284
Luggage Boot    0.457284
Safety          0.457284
CarClass        0.457284
dtype: float64


In [7]:
a=pd.Series([1,2,3,4,4])
a.value_counts()

4    2
3    1
2    1
1    1
dtype: int64

In [8]:
from sklearn import tree

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[df.columns[:-1]],df['CarClass'],random_state=42,test_size=0.2)
dt=tree.DecisionTreeClassifier(criterion='gini',max_depth=10)
x_train.head()

Cost maintenace   door person Luggage Boot Safety
107   vhigh      vhigh  5more   more          big   high
901     med      vhigh      3      4        small    med
1709    low        low  5more      2          big   high
706    high        med      4      2          med    med
678    high        med      3      2          med    low

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
    df[i]=le.fit_transform(df[i])
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[df.columns[:-1]],df['CarClass'],random_state=42,test_size=0.2)
dt=tree.DecisionTreeClassifier()
x_train.head()
dt.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [12]:
print("The accuracy is :", dt.score(x_test,y_test))

The accuracy is : 0.973988439306


In [19]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred=dt.predict(x_test)
print("The Confusion Matrix is \n",confusion_matrix(y_pred,y_test))
print("The Confusion Matrix is \n",classification_report(y_pred,y_test))

The Confusion Matrix is 
 [[ 76   1   0   1]
 [  6  10   0   0]
 [  1   0 235   0]
 [  0   0   0  16]]
The Confusion Matrix is 
              precision    recall  f1-score   support

          0       0.92      0.97      0.94        78
          1       0.91      0.62      0.74        16
          2       1.00      1.00      1.00       236
          3       0.94      1.00      0.97        16

avg / total       0.97      0.97      0.97       346



In [22]:
#Visualisation Part
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

dot_data = StringIO()

export_graphviz(dt, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

InvocationException: GraphViz's executables not found